# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emballages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_info',
            name='menu2',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='data_info',
            name='menu3',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='data_info',
            name='menu4',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='data_info',
            name='menu5',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='data_info',
            name='menu6',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='clients',
            name='imagen401',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='clients',
            name='titulo_401',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='boton_501',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='pregunta51',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='pregunta52',
            field=models.EmailField(max_length=75, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='pregunta53',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='pregunta54',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='titulo_501',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data_info',
            name='correo',
            field=models.EmailField(max_length=75, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data_info',
            name='idioma',
            field=models.CharField(default=b'es', max_length=2, blank=True, choices=[(b'en', b'English'), (b'es', b'Espa\xc3\xb1ol')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data_info',
            name='logo',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data_info',
            name='menu1',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data_info',
            name='telf1',
            field=models.CharField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data_info',
            name='telf2',
            field=models.CharField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data_info',
            name='telf3',
            field=models.CharField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='boton_201',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='boton_251',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='boton_252',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='boton_253',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='cuestionario',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_220',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_221',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_222',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_223',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_224',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_225',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_226',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_227',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_228',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_229',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img220',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img221',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img222',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img223',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img224',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img225',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img226',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img227',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img228',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='empaque_img229',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen201',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen211',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen212',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen213',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen231',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen232',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen241',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen242',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen243',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2501',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2502',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2503',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2504',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2505',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2506',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2507',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2508',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2509',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2510',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2511',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2512',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2513',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2514',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2515',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2516',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2517',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2518',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2519',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2520',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2521',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2522',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2523',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2524',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2525',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2526',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2527',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2528',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2529',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2530',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2531',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2532',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2533',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2534',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2535',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2536',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2537',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2538',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2539',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2540',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2541',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2542',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2543',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2544',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='imagen2545',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='pregunta21',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='pregunta22',
            field=models.EmailField(max_length=75, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='pregunta23',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='pregunta24',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2501',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2502',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2503',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2504',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2505',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2506',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2507',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2508',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2509',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2510',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2511',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2512',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2513',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2514',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2515',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario201',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario211',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario212',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario213',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2501',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2502',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2503',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2504',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2505',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2506',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2507',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2508',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2509',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2510',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2511',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2512',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2513',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2514',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2515',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_201',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_211',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_212',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_213',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_231',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_232',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_241',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_242',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_243',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='titulo_251',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='footer',
            name='titulo_601',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen111',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen112',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen113',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen114',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen115',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen116',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen121',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen122',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen131',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen132',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen133',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen134',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen135',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen136',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen141',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen151',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen152',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen153',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen154',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen155',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='imagen156',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='img_certificado',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='subtitulo131',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='subtitulo132',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario111',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario121',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario131',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario132',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario141',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario151',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario152',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='titulo_111',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='titulo_121',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='titulo_131',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='titulo_141',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='titulo_151',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='titulo_152',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='boton_301',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='imagen301',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='imagen311',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='imagen312',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='imagen321',
            field=models.ImageField(upload_to=b'imgs', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='subtitulo311',
            field=models.CharField(max_length=25, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario301',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario311',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario312',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario313',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario314',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario315',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario316',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario317',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario318',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario319',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario321',
            field=models.TextField(blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='titulo_301',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='titulo_321',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
    ]
